# Generated by Django 3.2.6 on 2021-09-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
