# Generated by Django 3.2.6 on 2021-09-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False},
        ),
    ]
