# Generated by Django 3.2.6 on 2021-09-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_alter_profile_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
