# Generated by Django 3.2.6 on 2021-09-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
